# - ITMO.Sync

default_calendar_prefix: "ITMO"

summary_template: "{title} — {type}. {format}"
description_template: "Преподаватель: {teacher}\n\n{note}"

booking_summary_template: "Бронирование: {title}"
booking_description_template: "{format}\n\n{note}"

ignore:
  - match: "История России и мира в ХХ веке"
    format: REMOTE
  - match: "Теория вероятности"
    type: LECTURE

renames:
  - "English B1.2 / Английский язык B1.2": "Английский язык B1.2"
  - "Объектно-ориентированное проектирование и программирование на C#": "Объектно-ориентированное проектирование"

format_labels:
  1: "Гибрид"
  2: "Очно"
  3: "Дистанционно"
