# - ITMO.Sync

# Парсинг

# fetch_start: "09-01"
# fetch_end: "06-30"
# default_calendar_prefix: "ИТМО"
# include_url_field: true
# include_location: true


# Шаблоны
# Доступные переменные: {title}, {type}, {label}, {teacher}, {format}, {location}, {url}, {note}

# summary_template: "{label} {title} — {type}. {format}"
# description_template: "Преподаватель: {teacher}\n{format}\n{note}"

# booking_summary_template: "{label} Бронирование: {title}"
# booking_description_template: "{format}\n\n{note}"


# Переименование типов
# Оставляй левую часть неизменной, правой — переименовывай

# type_names:
#   "Лекции": "Лекция"
#   "Практические занятия": "Практика"
#   "Лабораторные занятия": "Лабораторная"
#   "Занятия спортом": "Спорт"
#   "Экстернат": "Экстернат"
#   "Экзамен": "Экзамен"
#   "Зачет": "Зачет"
#   "Дифференцированный зачет": "Диф. зачет"
#   "Консультация": "Консультация"
#   "Бронирования": "Бронирование"


# Эмодзи
# Оставляй левую часть неизменной, правой — переименовывай

# labels:
#   "Лекции": "📚"
#   "Практические занятия": "🧪"
#   "Лабораторные занятия": "🔬"
#   "Занятия спортом": "🏋️"
#   "Экстернат": "🌍"
#   "Экзамен": "🔥"
#   "Зачет": "✅"
#   "Дифференцированный зачет": "💯"
#   "Консультация": "💬"
#   "Бронирования": "🗓️"

# default_label: "📝"


# Форматы проведения
# 1 - гибрид, 2 - очно, 3 - дистант

# format_labels:
#   1: "Смешанный формат"
#   2: "Очно"
#   3: "Дистанционно"
