rules:
  ignore:
    - match: "История России и мира в ХХ веке"
      format: REMOTE

    - match: "Теория вероятности"
      type: LECTURE

  renames:
    - "English B1.2 / Английский язык B1.2": "Английский язык"
    - "Объектно-ориентированное проектирование и программирование на C#": "Объектно-ориентированное проектирование"
